2. Back-end/TOP10OWASP/TOP10OWASP/Controllers/BrokenAuthenticationAndSessionManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TOP10OWASP.Common;
using TOP10OWASP.Models;

namespace TOP10OWASP.Controllers
{
    public class BrokenAuthenticationAndSessionManagementController : Controller
    {
        // GET: BrokenAuthenticationAndSessionManagement
        TOP10OWASPEntities1 _db = new TOP10OWASPEntities1();
        cEncode code = new cEncode();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login(string username, string password)
        {
            var model = _db.USERACCOUNTs.Where(x => x.USERNAME.Equals(username) && x.PASSWORD.Equals(password)).SingleOrDefault();

            var userSession = new UserLogin();
            userSession.role = model.ROLE;            
            Session.Add("SESSION_ROLE", userSession);

            string roles = model.ROLE;
            HttpCookie myCookie = new HttpCookie("dataType", roles);
            myCookie.Expires = DateTime.Now.AddDays(1);
            Response.Cookies.Add(myCookie);
            return View(model);
        }

        public ActionResult LoginWithOwasp(string username, string password)
        {
            var model = _db.USERACCOUNTOWASPs.Where(x => x.USERNAME.Equals(username)).SingleOrDefault();

            if(model != null)
            {
                string passwordEncodeUser = code.EncodeFromUser(password);
                string passwordEncodeFromDb = code.EncodeFromDb(model.PASSWORD);

                if (passwordEncodeUser.Equals(passwordEncodeFromDb))
                {
                    var userSession = new UserLogin();
                    userSession.role = model.ROLE;
                    Session.Add("SESSION_ROLE", userSession);

                    
                    HttpCookie myCookie = new HttpCookie("USER_SESSION", code.EncodeFromUser(model.ID.ToString()));
                    myCookie.Expires = DateTime.Now.AddDays(1);
                    Response.Cookies.Add(myCookie);
                    return View(model);
                }
                else
                {
                    return RedirectToAction("Index", "Error");
                }
            }
            return View();
        }
    }
}

2. Back-end/TOP10OWASP/TOP10OWASP/Views/BrokenAuthenticationAndSessionManagement/Index.cshtml
<div class="row">
    <div class="col-12">
        <div class="tab">
            <div class="page-number h2">
                <span class="number">2.</span> Broken Authenticaton and Session
                Management
                <a href="/" class="mr-auto">Back to index</a>
            </div>

            <div id="smartwizard">
                <ul class="nav">
                    <li>
                        <a class="nav-link" href="#step-1">
                            Tìm hiểu về Broken Authenticaton and Session Management
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="#step-2"> Hướng giải quyết </a>
                    </li>
                    <li>
                        <a class="nav-link" href="#step-3"> Demo sau khi Ngăn lỗi </a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div id="step-1" class="tab-pane" role="tabpanel">
                        <div class="content">
                            <p>
                                Để kiểm tra bạn có mắc lỗi không? hãy xem lại website
                                của bạn theo danh sách dưới đây:
                            </p>
                            <ol class="ml-5">
                                <li>
                                    <p>
                                        Những thông tin tài khoản có được bảo vệ khi lưu trữ
                                        dưới dạng băm hoặc mã hóa không ?
                                    </p>
                                </li>
                                <li>
                                    <p>
                                        Thông tin có thể bị đoán ra hoặc thay thế vì những
                                        điểm yếu trong các chương trình quản lý tài khoản hay
                                        không ? (tạo tài khoản, đồi password, lấy lại
                                        password, điểm yếu trong id phiên làm việc)
                                    </p>
                                </li>
                                <li>
                                    <p>ID phiên làm việc có hiển thị trong URL không?</p>
                                </li>
                                <li>
                                    <p>
                                        ID phiên làm việc có thể bị giả mạo bằng các phương
                                        pháp định hình phiên làm việc hay không?
                                    </p>
                                </li>
                                <li>
                                    <p>
                                        Id phiên làm việc có thời gian chờ không và người dùng
                                        có thể đăng xuất không ?
                                    </p>
                                </li>
                                <li>
                                    <p>
                                        Id phiên làm việc có thay đổi sau khi người dùng đăng
                                        nhập lại không?
                                    </p>
                                </li>
                                <li>
                                    <p>
                                        Password, Id phiên làm việc và những thông tin khác có
                                        được gửi đi sử dụng TLS connection không?
                                    </p>
                                </li>
                            </ol>
                            <p>Ví dụ thực hiện tấn công khi phía lập trình quản lý cẩn thận:</p>
                            <div class="ml-4">
                                <p>Giờ hãy thử truy cập vào website với cả 2 toàn khoản <span class="high-light">admin - admin</span> hoặc <span class="high-light">user1 - user1</span></p>
                                <p>Sau khi đăng nhập hãy copy đường dẫn sau đây lên website của bạn <span class="high-light">https://localhost:44343/admin</span></p>
                                <p>Với quyền admin, Bạn được welcome. Tuy nhiên với quyền là user hệ thống sẽ hiển thị bạn không đủ quyền truy cập. Vậy để thực hiện tấn công ta làm như sau:</p>
                                <ol class="ml-5">
                                    <li>
                                        <p>Nhấn tổ hợp <span class="high-light">Ctrl + Shift + I</span></p>
                                    </li>
                                    <li>
                                        <p>Chỉnh sang tab Application, nhìn sang thanh chức năng bên tay trái, chọn vào Cookies, chọn vào localhost</p>
                                    </li>
                                    <li>
                                        <p>Click double chuột vào ô Value của dataType và thay đổi thành admin. Sau đó thực hiện lại việc tấn công</p>
                                    </li>
                                </ol>
                            </div>
                        </div>
                        <div class="demo d-flex">
                            <div class="form-group">
                                @using (Html.BeginForm("Login", "BrokenAuthenticationAndSessionManagement", FormMethod.Post))
                                {
                                    <input type="text"
                                           class="form-control font-small mb-3"
                                           name="username"
                                           placeholder="Nhập vào tài khoản" />
                                    <input type="password"
                                           class="form-control font-small mb-3"
                                           name="password"
                                           placeholder="Nhập vào mật khẩu" />
                                    <button type="submit"
                                            class="btn btn-primary btn-sm px-3 py-1">
                                        Đăng nhập
                                    </button>
                                }
                            </div>
                        </div>
                    </div>
                    <div id="step-2" class="tab-pane" role="tabpanel">
                        <p>Các cách để khắc phục việc này:</p>
                        <ol class="ml-5">
                            <li>
                                <p>
                                    Sử dụng SSL, attacker sẽ khó tấn công vào cookies hơn
                                </p>
                            </li>
                            <li>
                                <p>Sử dụng HTTPOnly Cookie</p>
                            </li>
                            <li>
                                <p>Thiết lập timeOut cho SESSION, COOKIES</p>
                            </li>
                            <li>
                                <p>
                                    Tuyệt đối không để lộ SessionID qua URL, thay vào đó sử
                                    dụng Cookie
                                </p>
                            </li>
                            <li>
                                <p>Mã hóa cookie khi cần thiết</p>
                            </li>
                            <li>
                                <p>Không ghi SessionID ra log</p>
                            </li>
                            <li>
                                <p>
                                    Kiểm tra password cũ khi đổi. Gửi email xác nhận tới
                                    email cũ nếu đổi email
                                </p>
                            </li>
                        </ol>
                    </div>
                    <div id="step-3" class="tab-pane" role="tabpanel">
                        <div class="content">
                            <p>Giờ hãy thử thực hiện việc tấn công bằng việc thay đổi Cookies như lúc tìm hiểu và xem kết quả</p>
                            <p>Tuy nhiên hãy thay đổi đường dẫn thành <span class="high-light">https://localhost:44343/adminowasp</span></p>
                        </div>
                        <div class="demo d-flex">
                            <div class="form-group">
                                @using (Html.BeginForm("LoginWithOwasp", "BrokenAuthenticationAndSessionManagement", FormMethod.Post))
                                {
                                    <input type="text"
                                           class="form-control font-small mb-3"
                                           name="username"
                                           placeholder="Nhập vào tài khoản" />
                                    <input type="password"
                                           class="form-control font-small mb-3"
                                           name="password"
                                           placeholder="Nhập vào mật khẩu" />
                                    <button type="submit"
                                            class="btn btn-primary btn-sm px-3 py-1">
                                        Đăng nhập
                                    </button>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

2. Back-end/TOP10OWASP/TOP10OWASP/Views/BrokenAuthenticationAndSessionManagement/Login.cshtml
@model TOP10OWASP.Models.USERACCOUNT
@{
    ViewBag.Title = "Login";
}

<h3>Hello @Model.NAME</h3>

2. Back-end/TOP10OWASP/TOP10OWASP/Views/BrokenAuthenticationAndSessionManagement/LoginWithOwasp.cshtml
@model TOP10OWASP.Models.USERACCOUNTOWASP
<h4>Hello @Model.NAME</h4>

<a href="@Url.Action("Index", "BrokenAuthenticationAndSessionManagement")">Trở lại trang</a>