2. Back-end/TOP10OWASP/TOP10OWASP/Controllers/MissingFunctionLevelAccessControlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TOP10OWASP.Models;
using TOP10OWASP.Common;

namespace TOP10OWASP.Controllers
{
    public class MissingFunctionLevelAccessControlController : Controller
    {
        // GET: MissingFunctionLevelAccessControl
        TOP10OWASPEntities1 _db = new TOP10OWASPEntities1();
        cEncode code = new cEncode();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoginWithOwasp(string username, string password)
        {
            var model = _db.USERACCOUNTOWASPs.Where(x => x.USERNAME.Equals(username)).SingleOrDefault();

            if (model != null)
            {
                string passwordEncodeUser = code.EncodeFromUser(password);
                string passwordEncodeFromDb = code.EncodeFromDb(model.PASSWORD);

                if (passwordEncodeUser.Equals(passwordEncodeFromDb))
                {
                    var userSession = new UserLogin();
                    userSession.role = model.ROLE;
                    Session.Add("session_role", userSession);


                    HttpCookie myCookie = new HttpCookie("user_session", code.EncodeFromUser(model.ID.ToString()));
                    myCookie.Expires = DateTime.Now.AddDays(1);
                    Response.Cookies.Add(myCookie);
                    return View(model);
                }
            }
            return View();
        }
    }
}

2. Back-end/TOP10OWASP/TOP10OWASP/Views/MissingFunctionLevelAccessControl/Index.cshtml
<div class="row">
    <div class="col-12">
        <div class="tab">
            <div class="page-number h2">
                <span class="number">7.</span> Missing Function Level Access
                Control
                <a href="/" class="mr-auto">Back to index</a>
            </div>

            <div id="smartwizard">
                <ul class="nav">
                    <li>
                        <a class="nav-link" href="#step-1">
                            Tìm hiểu về Missing Function Level Access Control
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="#step-2"> Hướng giải quyết </a>
                    </li>
                    <li>
                        <a class="nav-link" href="#step-3"> Demo sau khi Ngăn lỗi </a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div id="step-1" class="tab-pane" role="tabpanel">
                        <div class="content">
                            <p class="h4">Định nghĩa</p>
                            <div class="ml-4">
                                <p>
                                    Hầu hết các trang web đều có 1 hàm phân quyền cho người
                                    dùng. Nhưng nếu hàm đó không được đồng bộ thực hiện đúng
                                    đắn như phía người dùng thì kẻ tấn công có thể được lợi
                                    dụng lỗ hỏng này để tấn công vào trang web với những đặc
                                    quyền cao hơn.
                                </p>
                                <p>
                                    Đây chỉ là sai sót trong vấn đề phân quyền. Nó có nghĩa là
                                    khi một hàm được gọi trên máy chủ, quá trình phân quyền
                                    không chính xác. Các nhà phát triển dựa vào thực tế là
                                    phía máy chủ tạo ra giao diện người dùng và họ nghĩ rằng
                                    khách hàng không thể truy cập các chức năng nếu không được
                                    cung cấp bởi máy chủ.
                                </p>
                                <p>
                                    Tuy nhiên, kẻ tấn công luôn có thể yêu cầu các chức năng
                                    “ẩn” và sẽ không bị cản trở bởi việc giao diện người dùng
                                    không cho phép thực hiện các chức năng này. Hãy tưởng
                                    tượng trong giao diện người dùng chỉ có bảng điều
                                    khiển/admin và nút nếu người dùng thực sự là quản trị
                                    viên. Không có gì ngăn cản kẻ tấn công phát hiện ra những
                                    tính năng này và lạm dụng nó nếu không phân quyền.
                                </p>
                                <p>
                                    Thiệt hại có thể dẫn đến mất toàn bộ dữ liệu của doanh
                                    nghiệp của bạn.
                                </p>
                                <p>Hãy thử truy cập vào trang quản trị bằng cách dán đường link <span class="high-light">localhost:{your hosting}/admin/homeAdmin/Index2</span> lên thanh URL của bạn. Nếu phía server không ràng buộc kỹ càng thì Attackers có thể truy cập vào và phá hoại toàn bộ thông tin, dữ liệu của hệ thống</p>
                            </div>
                        </div>
                        
                    </div>
                    <div id="step-2" class="tab-pane" role="tabpanel">
                        <p class="h4">Làm thế nào để ngăn chặn?</p>
                        <ol class="ml-5">
                            <li>
                                <p>
                                    Phải yêu cầu truy cập, kiểm tra quyền của người dùng. Nếu người dùng thuộc
                                    tài khoản quản trị viên cho phép truy cập thẳng vào trang quản trị. Còn 
                                    người dùng chỉ thuộc quyền người dùng thì truy cập vào trang người dùng.
                                </p>
                            </li>
                            <li>
                                <p>
                                    Ở phía máy chủ, phải luôn được phân quyền một cách triệt
                                    để từ khâu thiết kế.
                                </p>
                            </li>
                            <li>
                                <p>
                                    Không có ngoại lệ – mọi lỗ hổng sẽ dẫn đến đủ các vấn đề
                                    nghiêm trọng.
                                </p>
                            </li>
                            <li>
                                <p>
                                    Kiểm định chặt chẽ các dữ liệu bị rò rĩ ở phía Client
                                    như SessionID, Cookie mà attackers có thể thay đổi nó để
                                    tấn công vào trang quản trị.
                                </p>
                            </li>
                        </ol>
                    </div>
                    <div id="step-3" class="tab-pane" role="tabpanel">
                        <div class="content">
                            <p>Giờ hãy thử tấn công lại bằng cách truy cập vào đường link như sau <span class="high-light">localhost:{your hosting}/adminowasp/HomeAdmin/Index2</span></p>
                            <p>Vậy hãy thử sau khi đăng nhập, ta tiếp tục truy cập vào đường link để xem kết quả với 2 tài khoản <span class="high-light">admin - admin</span> và <span class="high-light">user1 - user1</span></p>
                        </div>
                        <div class="demo d-flex">
                            <div class="form-group">
                                @using (Html.BeginForm("LoginWithOwasp", "MissingFunctionLevelAccessControl", FormMethod.Post))
                                {
                                    <input type="text"
                                           class="form-control font-small mb-3"
                                           name="username"
                                           placeholder="Nhập vào tài khoản" />
                                    <input type="password"
                                           class="form-control font-small mb-3"
                                           name="password"
                                           placeholder="Nhập vào mật khẩu" />
                                    <button type="submit"
                                            class="btn btn-primary btn-sm px-3 py-1">
                                        Đăng nhập
                                    </button>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

2. Back-end/TOP10OWASP/TOP10OWASP/Views/MissingFunctionLevelAccessControl/LoginWithOwasp.cshtml
@model TOP10OWASP.Models.USERACCOUNTOWASP
<h4>Hello @Model.NAME</h4>

<a href="@Url.Action("Index", "MissingFunctionLevelAccessControl")">Trở lại trang</a>